KSENROLL-10782:  kitchen sink URLs should not be excluded from spring security as unauthenticated access to those URLs ends up causing the following exception (after logging in):
org.kuali.rice.krad.exception.AuthenticationException: Blank User from
AuthenticationService - This should never happen.